### ISSUE TITLE
Unable to access the server

### ISSUE THREAD

**Issue by dandeperson** [castacks/TartanAviation#4]
Very excited that you are exposing such well-developed datasets in terminal airspace operations. I have been in great need of ADS-B trajectory data for my current tasks in recent days. I would appreciate your help in resolving this issue if possible.
`Failed to lookup kbtp/raw/2022
An error occurred: S3 operation failed; code: BadRequest, message: Bad request, resource: /tartanaviation-adsb/kbtp/raw/2022.zip, request_id: None, host_id: None, bucket_name: tartanaviation-adsb, object_name: kbtp/raw/2022.zip`

**Comment by jaypatrikar** [comment]
Fixed. The change to handle TLS certificate is pushed.
